name = "tabasco-server"
main = "src/index.ts"
compatibility_date = "2023-06-09"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tabasco-db"
database_id = "6794501a-d5a2-459b-8c32-d1c2d744dd0d"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
